language: php
sudo: required
dist: trusty
php:
    - 5.6
    - 7.0
    - 7.1
    - 7.2
    - master
    - nightly
matrix:
    fast_finish: true
    allow_failures:
        - php: master
        - php: nightly
os:
    - windows
    - linux
install:
    - travis_retry validate install --no-interaction
    - travis_retry composer install --no-interaction
cache:
    directories:
        - vendor
        - $HOME/.cache/composer
